import type { ProjectDetail } from "@/types";

const NOW = Math.floor(Date.now() / 1000);

export const askProjectFixture = (over: Partial<ProjectDetail> = {}): ProjectDetail => ({
  id: "prj_1",
  slug: "mou-pack",
  name: "Four MOUs",
  description: "Draft the four partner MOUs.",
  icon: null,
  color: null,
  board_slug: "mou",
  primary_path: null,
  archived: false,
  created_at: NOW - 30 * 86_400,
  goal: "Four signed MOUs",
  visibility: "shared",
  owner_user_id: "leo_owner",
  status: "active",
  cadence: "one_off",
  schedule: null,
  review_every: null,
  autonomy: "supervised",
  max_in_progress: 1,
  budget_usd_per_run: null,
  definition_of_done: null,
  target_audience: null,
  score_rubric: null,
  toolsets: "web,file",
  skills: "",
  due_at: null,
  host_profile: "default",
  cron_job_id: null,
  summary: null,
  summary_at: null,
  last_reviewed_at: null,
  next_run_at: null,
  outputs: [],
  members: [],
  profiles: [],
  contacts: [],
  links: {},
  progress: {
    rung: "outputs",
    label: "outputs",
    headline: "0 of 4 outputs accepted",
    accepted: 0,
    required: 4,
    cards: { total: 0, done: 0, running: 0, blocked: 0 },
  },
  score: null,
  health: "ok",
  runs: [],
  card_rollup: { total: 0, done: 0, running: 0, blocked: 0 },
  recent_events: [],
  ...over,
});
